apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: **********azure-aks:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials  # Refers to your secret
              key: username  # Matches the key in your secret
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: host
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: port
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: database
