apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  type: LoadBalancer  # Use LoadBalancer for external access, ClusterIP if only internal access is needed
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: nodejs-app  # This should match the label selector of your pods
